Create lint.yml
tenantcloud/ansible-role-software-common pull request #10
Opened 2020-09-11 17:22 UTC by odebretseni

2020-10-02 10:49 UTC, BrunIF requested changes

2020-10-02 10:49 UTC, BrunIF commented on tasks/install-ukrainian-language.yml
> +  template: src=info.txt.j2 dest=$HOME/Desktop/common_software.txt mode="0777"
Читабельність краща, якщо у декілька рядків. 
І надо постійно перевизначати mode?

2020-10-05 18:53 UTC, BrunIF requested changes

2020-10-05 18:53 UTC, BrunIF commented on README.md
> +<img src="https://github.com/tenantcloud/ansible-role-software-common/workflows/Yaml Lint/badge.svg?branch-master" alt="">
![image](https://user-images.githubusercontent.com/490917/95119710-11f7d000-0755-11eb-8298-7d0130bbde4b.png)

2020-10-06 09:24 UTC, BrunIF approved these changes

2020-10-06 09:35 UTC, vikfedkiv approved these changes

2020-10-06 09:36 UTC, merged